title: Deva Risny
email: risnydeva@gmail.com
description: Saya merupakan mahasiswa semester 2 prodi Teknik Informatika di Politeknik Negeri Lhokseumawe. Saya lahir di Lhokseumawe pada 17 Desember 2005. Saya anak ke 1 dari 3 bersaudara. Saya tinggal di alue awe.

url: 'https://devarisny.github.io/'

plugins:
 - jekyll-feed
 - jekyll-sitemap
 - jekyll-seo-tag